import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>LactoFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#122e49] to-[#15162c]">
        <div className="container bg-[#76b1af] flex flex-col items-center justify-center px-6 py-10">
          <h4 className="text-center text-3xl text-[#fcfaef]">Conheça o Método</h4>
          <h1 className="text-center text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Lacto<span className="text-[#c6302c]">Flow</span>{" "}
          </h1>
          <h1 className="font-extrabold text-[#122e49] text-[25px] lg:text-[31.25px] text-center mt-6 leading-[29.17px] tracking-[-25] mb-[14.4px]">
            Aprenda como aumentar a sua produção de leite e ofereça o melhor alimento do mundo ao seu bebê.
          </h1>
          <p className="mt-7 lg:mt-5 font-bold text-[16.67px] lg:text-[18.75px] leading-[22.9px] tracking-[-25] text-center">
            Assista a aula de introdução gratuitamente e você vai aprender 3 coisas:</p>
            <div className="flex items-center gap-x-4 mt-6 lg:mt-12">
              <div><div className="relative w-[36px] h-[36px] ">
                1
              </div></div>
              <p className="font-medium text-[15.67px] lg:text-[16.75px] leading-[22.9px] tracking-[-25]">Como criar um projeto protótipo e fazer a sua primeira venda em pouco tempo e gastando pouco dinheiro;</p>
            </div>
            <div className="flex items-center gap-x-4 mt-6 lg:mt-12">
              <div><div className="relative w-[36px] h-[36px] ">
                2
              </div></div>
              <p className="font-medium text-[15.67px] lg:text-[16.75px] leading-[22.9px] tracking-[-25]">Como criar um projeto protótipo e fazer a sua primeira venda em pouco tempo e gastando pouco dinheiro;</p>
            </div>
            <iframe className="w-full aspect-video rounded-md mt-8 mx-auto max-w-[22rem] lg:max-w-[53.25rem]" src="https://www.youtube.com/embed/EdrQPJZ77vY"></iframe>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
